version: "3.9"
services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
    - "9000:9000"
  # fetch-app-service:
  #   network_mode: host
  #   image: ":latest"
  #   volumes:
  #     - ${PWD}/services/fetch-app-service/.env:/root/services/fetch-app-service/.env
volumes:
  data: