version: "3.9"
services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  server_auth_app:
    build:
      context: ./services/auth-app
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
    - "9000:9000"
  server_fetch_app:
    build:
      context: ./services/fetch-app
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
    - "9001:9001"
volumes:
  data: